name: cerf_data_centers
channels:
    - conda-forge
dependencies:
    - python>=3.11
    - pip
    - pip:
        - cerf_data_centers
        - numpy>=2.2.6
        - pandas>=2.2.3
        - geopandas>=1.1.0
        - rasterio>=1.4.3
        - shapely>=2.1.1
        - PyYAML>=6.0.2
        - networkx>=3.5
        - tqdm>=4.67.1